/**
 * Generates a downloadable fix.sh bash script from security findings.
 *
 * The script:
 * - Asks for confirmation before making any changes
 * - Includes inline comments explaining each fix
 * - Uses safe defaults and stderr redirection
 * - Warns the user about risks before execution
 */

import type { AuditFinding } from '../utils/types';

export function generateFixScript(findings: AuditFinding[]): string {
  const timestamp = new Date().toISOString();
  const lines: string[] = [];

  lines.push('#!/bin/bash');
  lines.push('# ============================================================');
  lines.push('# Linux Hardening Fix Script');
  lines.push('# Generated by Linux Hardening Assistant');
  lines.push(`# Timestamp: ${timestamp}`);
  lines.push('# ============================================================');
  lines.push('#');
  lines.push('# IMPORTANT:');
  lines.push('#   1. Review EVERY command below before running this script.');
  lines.push('#   2. Test on a non-production system first.');
  lines.push('#   3. Ensure you have an alternative way to access the server');
  lines.push('#      (console, out-of-band management) in case SSH breaks.');
  lines.push('#   4. This script requires sudo/root privileges.');
  lines.push('#');
  lines.push('set -euo pipefail');
  lines.push('');
  lines.push('# ── Confirmation prompt ──────────────────────────────────────');
  lines.push('echo "============================================================"');
  lines.push('echo " Linux Hardening Fix Script"');
  lines.push('echo "============================================================"');
  lines.push('echo ""');
  lines.push('echo "This script will apply the following security hardening fixes:"');
  lines.push('echo ""');

  const seen = new Set<string>();
  const uniqueFindings = findings.filter((f) => {
    const cmd = (f.fix_command ?? '').trim();
    if (!cmd || seen.has(cmd)) return false;
    seen.add(cmd);
    return true;
  });

  for (const f of uniqueFindings) {
    lines.push(`echo "  - ${f.issue_name}"`);
  }

  lines.push('echo ""');
  lines.push('read -r -p "Apply all fixes? (yes/no): " CONFIRM');
  lines.push('if [[ "${CONFIRM}" != "yes" ]]; then');
  lines.push('  echo "Aborted. No changes were made."');
  lines.push('  exit 0');
  lines.push('fi');
  lines.push('echo ""');
  lines.push('');

  lines.push('# ── Remediation commands ─────────────────────────────────────');
  lines.push('');

  for (const f of uniqueFindings) {
    lines.push(`# ── ${f.issue_name} (${f.severity}) ──`);
    lines.push(`# Risk: ${f.explanation.replace(/\n/g, ' ').substring(0, 120)}`);
    lines.push(`# Recommendation: ${f.recommendation.replace(/\n/g, ' ').substring(0, 100)}`);
    lines.push('');

    // Multi-line fix_command support (commands joined with &&  or \n)
    const cmd = f.fix_command.trim();
    if (cmd.startsWith('#')) {
      // Already commented — output as-is
      lines.push(cmd);
    } else {
      lines.push(`echo "Applying: ${f.issue_name}..."`);
      lines.push(cmd);
      lines.push(`echo "  ✓ Done: ${f.issue_name}"`);
    }
    lines.push('');
  }

  lines.push('# ── Cleanup and final message ────────────────────────────────');
  lines.push('echo ""');
  lines.push('echo "============================================================"');
  lines.push('echo " Hardening fixes applied successfully."');
  lines.push('echo " Please reboot or restart affected services if required."');
  lines.push('echo " Review /var/log/auth.log and syslog for any issues."');
  lines.push('echo "============================================================"');
  lines.push('');

  return lines.join('\n') + '\n';
}
